services:
  - type: web
    name: file-sharing-app
    env: node
    region: ohio
    plan: free
    buildCommand: npm install
    startCommand: node deploy.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: "mongodb+srv://Vishwa:Vishwa@cluster0.l82ddp2.mongodb.net/?retryWrites=true&w=majority"
      - key: PORT
        value: "10000"
    healthCheckPath: /api/test
    healthCheckTimeout: 100
    autoDeploy: true
    numInstances: 1 