services:
  - type: web
    name: globalpad
    env: node
    buildCommand: npm install
    startCommand: node deploy.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    region: ohio
    plan: free
    healthCheckPath: /
    healthCheckTimeout: 100
    autoDeploy: true
    numInstances: 1 